# Site Settings
baseurl: "./portfolio"

# Blog Setting
blog: True

# Language of the website
lang: fr


# Page Settings
theme_settings:
  title: Mon portfolio

  experience_title: Réussites
  interests_title: Domaines d'intéret
  skills_title: Compétences
  projects_title: Projets

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Settings
sass:
  sass_dir: _sass
  style: :compressed
plugins: ['jekyll-paginate', 'jekyll-seo-tag']
bootstrap:
  assets: true

academicons:
  version: "1.9.1"
  integrity: "sha256-i1+4qU2G2860dGGIOJscdC30s9beBXjFfzjWLjBRsBg="
fontawesome:
  version: "5.15.4"
  integrity: "sha256-mUZM63G8m73Mcidfrv5E+Y61y7a12O5mW4ezU3bxqW4="
jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
