# action.yml
name: 'custom jekyll build'
description: 'generate my portfolio'
inputs:
  source_dir:
    description: 'path of your content to create portfolio'
    required: false
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.source_dir}}
